[package]
name = "cvag-client"
version = "0.1.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
edition = "2018"

[dependencies]
restson = "0.5.4"
serde = "1.0.104"
serde_derive = "1.0.104"
chrono = { version = "0.4.10", features = ["serde", "rustc-serialize"] }
